// vite-swc-jsx-ts/src/App.jsx
import React from 'react';

const App: React.FC = () => {
  return (
    <div className="app">
      <h1>Hello from Vite, SWC, Styled JSX, and TypeScript!</h1>
      <style jsx>{`
        .app {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          font-family: Arial, sans-serif;
          background-color: #f0f0f0;
        }
      `}</style>
    </div>
  );
};

export default App;

// vite/starter/src/App.vue
<template>
    <div id="app">
      <h1>Welcome to Necto Vite Demo</h1>
    </div>
  </template>
  
  <script>
  export default {
    name: 'App',
  };
  </script>
  
  <style>
  #app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
  </style>
